import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
export default function Home() {
  const router = useRouter();
  const { id } = router.query;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <Image src="/logo.svg" alt="trello logo" height="42" width="168" />
      </nav>

      <h3>Board by the User </h3>
      <h4>Board "{id}"</h4>
    </div>
  );
}
